# Most rows follow a simple rule; a few deliberately contradict it to make the dataset noisy.
module RandomForestData
  NOISY_ROWS = [
    # sunny
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "sunny", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "yes"},

    # overcast
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "overcast", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "no"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "no"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "overcast", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "yes"},

    # rainy
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "weak", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "cool",  day_type: "weekend", play: "yes"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "high",   temperature: "hot",   day_type: "weekend", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "cool",  day_type: "weekend", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekday", play: "yes"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "mild",  day_type: "weekend", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekday", play: "no"},
    {outlook: "rainy", wind: "strong", humidity: "normal", temperature: "hot",   day_type: "weekend", play: "no"}
  ].freeze
end